/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "cusp.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_cuspInit__SWIG_0 _wrap_cuspInit__SWIG_0 ""
extern void (*_wrap_cuspInit__SWIG_0)(void*);
static void (*x_wrap_cuspInit__SWIG_0)(void*) = _wrap_cuspInit__SWIG_0;

void
·_swig_wrap_cuspInit__SWIG_0(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspInit__SWIG_0, &p);
}



#pragma dynimport _wrap_cuspInit__SWIG_1 _wrap_cuspInit__SWIG_1 ""
extern void (*_wrap_cuspInit__SWIG_1)(void*);
static void (*x_wrap_cuspInit__SWIG_1)(void*) = _wrap_cuspInit__SWIG_1;

void
·_swig_wrap_cuspInit__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_cuspInit__SWIG_1, &p);
}



#pragma dynimport _wrap_cuspShutdown _wrap_cuspShutdown ""
extern void (*_wrap_cuspShutdown)(void*);
static void (*x_wrap_cuspShutdown)(void*) = _wrap_cuspShutdown;

void
·_swig_wrap_cuspShutdown(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspShutdown, &p);
}



#pragma dynimport _wrap_cuspMain _wrap_cuspMain ""
extern void (*_wrap_cuspMain)(void*);
static void (*x_wrap_cuspMain)(void*) = _wrap_cuspMain;

void
·_swig_wrap_cuspMain(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspMain, &p);
}



#pragma dynimport _wrap_cuspMainSigInt _wrap_cuspMainSigInt ""
extern void (*_wrap_cuspMainSigInt)(void*);
static void (*x_wrap_cuspMainSigInt)(void*) = _wrap_cuspMainSigInt;

void
·_swig_wrap_cuspMainSigInt(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspMainSigInt, &p);
}



#pragma dynimport _wrap_cuspMainRunning _wrap_cuspMainRunning ""
extern void (*_wrap_cuspMainRunning)(void*);
static void (*x_wrap_cuspMainRunning)(void*) = _wrap_cuspMainRunning;

void
·CuspMainRunning(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_cuspMainRunning, &p);
}



#pragma dynimport _wrap_cuspStopMain _wrap_cuspStopMain ""
extern void (*_wrap_cuspStopMain)(void*);
static void (*x_wrap_cuspStopMain)(void*) = _wrap_cuspStopMain;

void
·_swig_wrap_cuspStopMain(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspStopMain, &p);
}



#pragma dynimport _wrap_cuspProcessEvents _wrap_cuspProcessEvents ""
extern void (*_wrap_cuspProcessEvents)(void*);
static void (*x_wrap_cuspProcessEvents)(void*) = _wrap_cuspProcessEvents;

void
·_swig_wrap_cuspProcessEvents(struct {
  uint8 x[1];
} p)

{
  runtime·cgocall(x_wrap_cuspProcessEvents, &p);
}



#pragma dynimport _wrap_new_InStream__SWIG_0 _wrap_new_InStream__SWIG_0 ""
extern void (*_wrap_new_InStream__SWIG_0)(void*);
static void (*x_wrap_new_InStream__SWIG_0)(void*) = _wrap_new_InStream__SWIG_0;

void
·_swig_wrap_new_InStream__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_InStream__SWIG_0, &p);
}



#pragma dynimport _wrap_new_InStream__SWIG_1 _wrap_new_InStream__SWIG_1 ""
extern void (*_wrap_new_InStream__SWIG_1)(void*);
static void (*x_wrap_new_InStream__SWIG_1)(void*) = _wrap_new_InStream__SWIG_1;

void
·_swig_wrap_new_InStream__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_InStream__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_InStream _wrap_delete_InStream ""
extern void (*_wrap_delete_InStream)(void*);
static void (*x_wrap_delete_InStream)(void*) = _wrap_delete_InStream;

void
·_swig_wrap_delete_InStream(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_InStream, &p);
}



#pragma dynimport _wrap_InStream_swap _wrap_InStream_swap ""
extern void (*_wrap_InStream_swap)(void*);
static void (*x_wrap_InStream_swap)(void*) = _wrap_InStream_swap;

void
·_swig_wrap_InStream_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_swap, &p);
}



#pragma dynimport _wrap_InStream_isValid _wrap_InStream_isValid ""
extern void (*_wrap_InStream_isValid)(void*);
static void (*x_wrap_InStream_isValid)(void*) = _wrap_InStream_isValid;

void
·_swig_wrap_InStream_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_isValid, &p);
}



#pragma dynimport _wrap_InStream_read__SWIG_0 _wrap_InStream_read__SWIG_0 ""
extern void (*_wrap_InStream_read__SWIG_0)(void*);
static void (*x_wrap_InStream_read__SWIG_0)(void*) = _wrap_InStream_read__SWIG_0;

void
·_swig_wrap_InStream_read__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_read__SWIG_0, &p);
}



#pragma dynimport _wrap_InStream_read__SWIG_1 _wrap_InStream_read__SWIG_1 ""
extern void (*_wrap_InStream_read__SWIG_1)(void*);
static void (*x_wrap_InStream_read__SWIG_1)(void*) = _wrap_InStream_read__SWIG_1;

void
·_swig_wrap_InStream_read__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_read__SWIG_1, &p);
}



#pragma dynimport _wrap_InStream_reset _wrap_InStream_reset ""
extern void (*_wrap_InStream_reset)(void*);
static void (*x_wrap_InStream_reset)(void*) = _wrap_InStream_reset;

void
·_swig_wrap_InStream_reset(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_reset, &p);
}



#pragma dynimport _wrap_InStream_queuedOutOfOrder _wrap_InStream_queuedOutOfOrder ""
extern void (*_wrap_InStream_queuedOutOfOrder)(void*);
static void (*x_wrap_InStream_queuedOutOfOrder)(void*) = _wrap_InStream_queuedOutOfOrder;

void
·_swig_wrap_InStream_queuedOutOfOrder(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_queuedOutOfOrder, &p);
}



#pragma dynimport _wrap_InStream_queuedUnread _wrap_InStream_queuedUnread ""
extern void (*_wrap_InStream_queuedUnread)(void*);
static void (*x_wrap_InStream_queuedUnread)(void*) = _wrap_InStream_queuedUnread;

void
·_swig_wrap_InStream_queuedUnread(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_queuedUnread, &p);
}



#pragma dynimport _wrap_InStream_bytesReceived _wrap_InStream_bytesReceived ""
extern void (*_wrap_InStream_bytesReceived)(void*);
static void (*x_wrap_InStream_bytesReceived)(void*) = _wrap_InStream_bytesReceived;

void
·_swig_wrap_InStream_bytesReceived(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_InStream_bytesReceived, &p);
}



#pragma dynimport _wrap_new_OutStream__SWIG_0 _wrap_new_OutStream__SWIG_0 ""
extern void (*_wrap_new_OutStream__SWIG_0)(void*);
static void (*x_wrap_new_OutStream__SWIG_0)(void*) = _wrap_new_OutStream__SWIG_0;

void
·_swig_wrap_new_OutStream__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OutStream__SWIG_0, &p);
}



#pragma dynimport _wrap_new_OutStream__SWIG_1 _wrap_new_OutStream__SWIG_1 ""
extern void (*_wrap_new_OutStream__SWIG_1)(void*);
static void (*x_wrap_new_OutStream__SWIG_1)(void*) = _wrap_new_OutStream__SWIG_1;

void
·_swig_wrap_new_OutStream__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_OutStream__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_OutStream _wrap_delete_OutStream ""
extern void (*_wrap_delete_OutStream)(void*);
static void (*x_wrap_delete_OutStream)(void*) = _wrap_delete_OutStream;

void
·_swig_wrap_delete_OutStream(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_OutStream, &p);
}



#pragma dynimport _wrap_OutStream_swap _wrap_OutStream_swap ""
extern void (*_wrap_OutStream_swap)(void*);
static void (*x_wrap_OutStream_swap)(void*) = _wrap_OutStream_swap;

void
·_swig_wrap_OutStream_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_swap, &p);
}



#pragma dynimport _wrap_OutStream_isValid _wrap_OutStream_isValid ""
extern void (*_wrap_OutStream_isValid)(void*);
static void (*x_wrap_OutStream_isValid)(void*) = _wrap_OutStream_isValid;

void
·_swig_wrap_OutStream_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_isValid, &p);
}



#pragma dynimport _wrap_OutStream_getPriority _wrap_OutStream_getPriority ""
extern void (*_wrap_OutStream_getPriority)(void*);
static void (*x_wrap_OutStream_getPriority)(void*) = _wrap_OutStream_getPriority;

void
·_swig_wrap_OutStream_getPriority(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_getPriority, &p);
}



#pragma dynimport _wrap_OutStream_setPriority _wrap_OutStream_setPriority ""
extern void (*_wrap_OutStream_setPriority)(void*);
static void (*x_wrap_OutStream_setPriority)(void*) = _wrap_OutStream_setPriority;

void
·_swig_wrap_OutStream_setPriority(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_setPriority, &p);
}



#pragma dynimport _wrap_OutStream_write _wrap_OutStream_write ""
extern void (*_wrap_OutStream_write)(void*);
static void (*x_wrap_OutStream_write)(void*) = _wrap_OutStream_write;

void
·_swig_wrap_OutStream_write(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_write, &p);
}



#pragma dynimport _wrap_OutStream_shutdown _wrap_OutStream_shutdown ""
extern void (*_wrap_OutStream_shutdown)(void*);
static void (*x_wrap_OutStream_shutdown)(void*) = _wrap_OutStream_shutdown;

void
·_swig_wrap_OutStream_shutdown(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_shutdown, &p);
}



#pragma dynimport _wrap_OutStream_reset _wrap_OutStream_reset ""
extern void (*_wrap_OutStream_reset)(void*);
static void (*x_wrap_OutStream_reset)(void*) = _wrap_OutStream_reset;

void
·_swig_wrap_OutStream_reset(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_reset, &p);
}



#pragma dynimport _wrap_OutStream_queuedInflight _wrap_OutStream_queuedInflight ""
extern void (*_wrap_OutStream_queuedInflight)(void*);
static void (*x_wrap_OutStream_queuedInflight)(void*) = _wrap_OutStream_queuedInflight;

void
·_swig_wrap_OutStream_queuedInflight(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_queuedInflight, &p);
}



#pragma dynimport _wrap_OutStream_queuedToRetransmit _wrap_OutStream_queuedToRetransmit ""
extern void (*_wrap_OutStream_queuedToRetransmit)(void*);
static void (*x_wrap_OutStream_queuedToRetransmit)(void*) = _wrap_OutStream_queuedToRetransmit;

void
·_swig_wrap_OutStream_queuedToRetransmit(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_queuedToRetransmit, &p);
}



#pragma dynimport _wrap_OutStream_bytesSent _wrap_OutStream_bytesSent ""
extern void (*_wrap_OutStream_bytesSent)(void*);
static void (*x_wrap_OutStream_bytesSent)(void*) = _wrap_OutStream_bytesSent;

void
·_swig_wrap_OutStream_bytesSent(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OutStream_bytesSent, &p);
}



#pragma dynimport _wrap_Address_fromString _wrap_Address_fromString ""
extern void (*_wrap_Address_fromString)(void*);
static void (*x_wrap_Address_fromString)(void*) = _wrap_Address_fromString;

void
·_swig_wrap_Address_fromString(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Address_fromString, &p);
}



#pragma dynimport _wrap_new_Address__SWIG_0 _wrap_new_Address__SWIG_0 ""
extern void (*_wrap_new_Address__SWIG_0)(void*);
static void (*x_wrap_new_Address__SWIG_0)(void*) = _wrap_new_Address__SWIG_0;

void
·_swig_wrap_new_Address__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Address__SWIG_0, &p);
}



#pragma dynimport _wrap_new_Address__SWIG_1 _wrap_new_Address__SWIG_1 ""
extern void (*_wrap_new_Address__SWIG_1)(void*);
static void (*x_wrap_new_Address__SWIG_1)(void*) = _wrap_new_Address__SWIG_1;

void
·_swig_wrap_new_Address__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Address__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_Address _wrap_delete_Address ""
extern void (*_wrap_delete_Address)(void*);
static void (*x_wrap_delete_Address)(void*) = _wrap_delete_Address;

void
·_swig_wrap_delete_Address(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Address, &p);
}



#pragma dynimport _wrap_Address_swap _wrap_Address_swap ""
extern void (*_wrap_Address_swap)(void*);
static void (*x_wrap_Address_swap)(void*) = _wrap_Address_swap;

void
·_swig_wrap_Address_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Address_swap, &p);
}



#pragma dynimport _wrap_Address_isValid _wrap_Address_isValid ""
extern void (*_wrap_Address_isValid)(void*);
static void (*x_wrap_Address_isValid)(void*) = _wrap_Address_isValid;

void
·_swig_wrap_Address_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Address_isValid, &p);
}



#pragma dynimport _wrap_Address_toString _wrap_Address_toString ""
extern void (*_wrap_Address_toString)(void*);
static void (*x_wrap_Address_toString)(void*) = _wrap_Address_toString;

void
·_swig_wrap_Address_toString(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_Address_toString, &p);
}



#pragma dynimport _wrap_PublicKeySuite_isValid _wrap_PublicKeySuite_isValid ""
extern void (*_wrap_PublicKeySuite_isValid)(void*);
static void (*x_wrap_PublicKeySuite_isValid)(void*) = _wrap_PublicKeySuite_isValid;

void
·_swig_wrap_PublicKeySuite_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuite_isValid, &p);
}



#pragma dynimport _wrap_PublicKeySuite_name _wrap_PublicKeySuite_name ""
extern void (*_wrap_PublicKeySuite_name)(void*);
static void (*x_wrap_PublicKeySuite_name)(void*) = _wrap_PublicKeySuite_name;

void
·_swig_wrap_PublicKeySuite_name(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuite_name, &p);
}



#pragma dynimport _wrap_PublicKeySuite_cost _wrap_PublicKeySuite_cost ""
extern void (*_wrap_PublicKeySuite_cost)(void*);
static void (*x_wrap_PublicKeySuite_cost)(void*) = _wrap_PublicKeySuite_cost;

void
·_swig_wrap_PublicKeySuite_cost(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuite_cost, &p);
}



#pragma dynimport _wrap_delete_PublicKeySuite _wrap_delete_PublicKeySuite ""
extern void (*_wrap_delete_PublicKeySuite)(void*);
static void (*x_wrap_delete_PublicKeySuite)(void*) = _wrap_delete_PublicKeySuite;

void
·_swig_wrap_delete_PublicKeySuite(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_PublicKeySuite, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_all _wrap_PublicKeySuiteSet_all ""
extern void (*_wrap_PublicKeySuiteSet_all)(void*);
static void (*x_wrap_PublicKeySuiteSet_all)(void*) = _wrap_PublicKeySuiteSet_all;

void
·_swig_wrap_PublicKeySuiteSet_all(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_all, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_defaults _wrap_PublicKeySuiteSet_defaults ""
extern void (*_wrap_PublicKeySuiteSet_defaults)(void*);
static void (*x_wrap_PublicKeySuiteSet_defaults)(void*) = _wrap_PublicKeySuiteSet_defaults;

void
·_swig_wrap_PublicKeySuiteSet_defaults(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_defaults, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_isEmpty _wrap_PublicKeySuiteSet_isEmpty ""
extern void (*_wrap_PublicKeySuiteSet_isEmpty)(void*);
static void (*x_wrap_PublicKeySuiteSet_isEmpty)(void*) = _wrap_PublicKeySuiteSet_isEmpty;

void
·_swig_wrap_PublicKeySuiteSet_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_isEmpty, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_contains _wrap_PublicKeySuiteSet_contains ""
extern void (*_wrap_PublicKeySuiteSet_contains)(void*);
static void (*x_wrap_PublicKeySuiteSet_contains)(void*) = _wrap_PublicKeySuiteSet_contains;

void
·_swig_wrap_PublicKeySuiteSet_contains(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_contains, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_element _wrap_PublicKeySuiteSet_element ""
extern void (*_wrap_PublicKeySuiteSet_element)(void*);
static void (*x_wrap_PublicKeySuiteSet_element)(void*) = _wrap_PublicKeySuiteSet_element;

void
·_swig_wrap_PublicKeySuiteSet_element(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_element, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_cheapest _wrap_PublicKeySuiteSet_cheapest ""
extern void (*_wrap_PublicKeySuiteSet_cheapest)(void*);
static void (*x_wrap_PublicKeySuiteSet_cheapest)(void*) = _wrap_PublicKeySuiteSet_cheapest;

void
·_swig_wrap_PublicKeySuiteSet_cheapest(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_cheapest, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_iterator _wrap_PublicKeySuiteSet_iterator ""
extern void (*_wrap_PublicKeySuiteSet_iterator)(void*);
static void (*x_wrap_PublicKeySuiteSet_iterator)(void*) = _wrap_PublicKeySuiteSet_iterator;

void
·_swig_wrap_PublicKeySuiteSet_iterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_iterator, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_toMask _wrap_PublicKeySuiteSet_toMask ""
extern void (*_wrap_PublicKeySuiteSet_toMask)(void*);
static void (*x_wrap_PublicKeySuiteSet_toMask)(void*) = _wrap_PublicKeySuiteSet_toMask;

void
·_swig_wrap_PublicKeySuiteSet_toMask(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_toMask, &p);
}



#pragma dynimport _wrap_PublicKeySuiteSet_fromMask _wrap_PublicKeySuiteSet_fromMask ""
extern void (*_wrap_PublicKeySuiteSet_fromMask)(void*);
static void (*x_wrap_PublicKeySuiteSet_fromMask)(void*) = _wrap_PublicKeySuiteSet_fromMask;

void
·_swig_wrap_PublicKeySuiteSet_fromMask(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKeySuiteSet_fromMask, &p);
}



#pragma dynimport _wrap_delete_PublicKeySuiteSet _wrap_delete_PublicKeySuiteSet ""
extern void (*_wrap_delete_PublicKeySuiteSet)(void*);
static void (*x_wrap_delete_PublicKeySuiteSet)(void*) = _wrap_delete_PublicKeySuiteSet;

void
·_swig_wrap_delete_PublicKeySuiteSet(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_PublicKeySuiteSet, &p);
}



#pragma dynimport _wrap_SymmetricSuite_isValid _wrap_SymmetricSuite_isValid ""
extern void (*_wrap_SymmetricSuite_isValid)(void*);
static void (*x_wrap_SymmetricSuite_isValid)(void*) = _wrap_SymmetricSuite_isValid;

void
·_swig_wrap_SymmetricSuite_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuite_isValid, &p);
}



#pragma dynimport _wrap_SymmetricSuite_name _wrap_SymmetricSuite_name ""
extern void (*_wrap_SymmetricSuite_name)(void*);
static void (*x_wrap_SymmetricSuite_name)(void*) = _wrap_SymmetricSuite_name;

void
·_swig_wrap_SymmetricSuite_name(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuite_name, &p);
}



#pragma dynimport _wrap_SymmetricSuite_cost _wrap_SymmetricSuite_cost ""
extern void (*_wrap_SymmetricSuite_cost)(void*);
static void (*x_wrap_SymmetricSuite_cost)(void*) = _wrap_SymmetricSuite_cost;

void
·_swig_wrap_SymmetricSuite_cost(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuite_cost, &p);
}



#pragma dynimport _wrap_delete_SymmetricSuite _wrap_delete_SymmetricSuite ""
extern void (*_wrap_delete_SymmetricSuite)(void*);
static void (*x_wrap_delete_SymmetricSuite)(void*) = _wrap_delete_SymmetricSuite;

void
·_swig_wrap_delete_SymmetricSuite(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_SymmetricSuite, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_all _wrap_SymmetricSuiteSet_all ""
extern void (*_wrap_SymmetricSuiteSet_all)(void*);
static void (*x_wrap_SymmetricSuiteSet_all)(void*) = _wrap_SymmetricSuiteSet_all;

void
·_swig_wrap_SymmetricSuiteSet_all(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_all, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_defaults _wrap_SymmetricSuiteSet_defaults ""
extern void (*_wrap_SymmetricSuiteSet_defaults)(void*);
static void (*x_wrap_SymmetricSuiteSet_defaults)(void*) = _wrap_SymmetricSuiteSet_defaults;

void
·_swig_wrap_SymmetricSuiteSet_defaults(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_defaults, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_isEmpty _wrap_SymmetricSuiteSet_isEmpty ""
extern void (*_wrap_SymmetricSuiteSet_isEmpty)(void*);
static void (*x_wrap_SymmetricSuiteSet_isEmpty)(void*) = _wrap_SymmetricSuiteSet_isEmpty;

void
·_swig_wrap_SymmetricSuiteSet_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_isEmpty, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_contains _wrap_SymmetricSuiteSet_contains ""
extern void (*_wrap_SymmetricSuiteSet_contains)(void*);
static void (*x_wrap_SymmetricSuiteSet_contains)(void*) = _wrap_SymmetricSuiteSet_contains;

void
·_swig_wrap_SymmetricSuiteSet_contains(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_contains, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_element _wrap_SymmetricSuiteSet_element ""
extern void (*_wrap_SymmetricSuiteSet_element)(void*);
static void (*x_wrap_SymmetricSuiteSet_element)(void*) = _wrap_SymmetricSuiteSet_element;

void
·_swig_wrap_SymmetricSuiteSet_element(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_element, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_cheapest _wrap_SymmetricSuiteSet_cheapest ""
extern void (*_wrap_SymmetricSuiteSet_cheapest)(void*);
static void (*x_wrap_SymmetricSuiteSet_cheapest)(void*) = _wrap_SymmetricSuiteSet_cheapest;

void
·_swig_wrap_SymmetricSuiteSet_cheapest(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_cheapest, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_iterator _wrap_SymmetricSuiteSet_iterator ""
extern void (*_wrap_SymmetricSuiteSet_iterator)(void*);
static void (*x_wrap_SymmetricSuiteSet_iterator)(void*) = _wrap_SymmetricSuiteSet_iterator;

void
·_swig_wrap_SymmetricSuiteSet_iterator(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_iterator, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_toMask _wrap_SymmetricSuiteSet_toMask ""
extern void (*_wrap_SymmetricSuiteSet_toMask)(void*);
static void (*x_wrap_SymmetricSuiteSet_toMask)(void*) = _wrap_SymmetricSuiteSet_toMask;

void
·_swig_wrap_SymmetricSuiteSet_toMask(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_toMask, &p);
}



#pragma dynimport _wrap_SymmetricSuiteSet_fromMask _wrap_SymmetricSuiteSet_fromMask ""
extern void (*_wrap_SymmetricSuiteSet_fromMask)(void*);
static void (*x_wrap_SymmetricSuiteSet_fromMask)(void*) = _wrap_SymmetricSuiteSet_fromMask;

void
·_swig_wrap_SymmetricSuiteSet_fromMask(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SymmetricSuiteSet_fromMask, &p);
}



#pragma dynimport _wrap_delete_SymmetricSuiteSet _wrap_delete_SymmetricSuiteSet ""
extern void (*_wrap_delete_SymmetricSuiteSet)(void*);
static void (*x_wrap_delete_SymmetricSuiteSet)(void*) = _wrap_delete_SymmetricSuiteSet;

void
·_swig_wrap_delete_SymmetricSuiteSet(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_SymmetricSuiteSet, &p);
}



#pragma dynimport _wrap_new_PublicKey__SWIG_0 _wrap_new_PublicKey__SWIG_0 ""
extern void (*_wrap_new_PublicKey__SWIG_0)(void*);
static void (*x_wrap_new_PublicKey__SWIG_0)(void*) = _wrap_new_PublicKey__SWIG_0;

void
·_swig_wrap_new_PublicKey__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_PublicKey__SWIG_0, &p);
}



#pragma dynimport _wrap_new_PublicKey__SWIG_1 _wrap_new_PublicKey__SWIG_1 ""
extern void (*_wrap_new_PublicKey__SWIG_1)(void*);
static void (*x_wrap_new_PublicKey__SWIG_1)(void*) = _wrap_new_PublicKey__SWIG_1;

void
·_swig_wrap_new_PublicKey__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_PublicKey__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_PublicKey _wrap_delete_PublicKey ""
extern void (*_wrap_delete_PublicKey)(void*);
static void (*x_wrap_delete_PublicKey)(void*) = _wrap_delete_PublicKey;

void
·_swig_wrap_delete_PublicKey(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_PublicKey, &p);
}



#pragma dynimport _wrap_PublicKey_swap _wrap_PublicKey_swap ""
extern void (*_wrap_PublicKey_swap)(void*);
static void (*x_wrap_PublicKey_swap)(void*) = _wrap_PublicKey_swap;

void
·_swig_wrap_PublicKey_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKey_swap, &p);
}



#pragma dynimport _wrap_PublicKey_isValid _wrap_PublicKey_isValid ""
extern void (*_wrap_PublicKey_isValid)(void*);
static void (*x_wrap_PublicKey_isValid)(void*) = _wrap_PublicKey_isValid;

void
·_swig_wrap_PublicKey_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKey_isValid, &p);
}



#pragma dynimport _wrap_PublicKey_toString _wrap_PublicKey_toString ""
extern void (*_wrap_PublicKey_toString)(void*);
static void (*x_wrap_PublicKey_toString)(void*) = _wrap_PublicKey_toString;

void
·_swig_wrap_PublicKey_toString(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_PublicKey_toString, &p);
}



#pragma dynimport _wrap_PublicKey_suite _wrap_PublicKey_suite ""
extern void (*_wrap_PublicKey_suite)(void*);
static void (*x_wrap_PublicKey_suite)(void*) = _wrap_PublicKey_suite;

void
·_swig_wrap_PublicKey_suite(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PublicKey_suite, &p);
}



#pragma dynimport _wrap_new_PrivateKey__SWIG_0 _wrap_new_PrivateKey__SWIG_0 ""
extern void (*_wrap_new_PrivateKey__SWIG_0)(void*);
static void (*x_wrap_new_PrivateKey__SWIG_0)(void*) = _wrap_new_PrivateKey__SWIG_0;

void
·_swig_wrap_new_PrivateKey__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_PrivateKey__SWIG_0, &p);
}



#pragma dynimport _wrap_new_PrivateKey__SWIG_1 _wrap_new_PrivateKey__SWIG_1 ""
extern void (*_wrap_new_PrivateKey__SWIG_1)(void*);
static void (*x_wrap_new_PrivateKey__SWIG_1)(void*) = _wrap_new_PrivateKey__SWIG_1;

void
·_swig_wrap_new_PrivateKey__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_PrivateKey__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_PrivateKey _wrap_delete_PrivateKey ""
extern void (*_wrap_delete_PrivateKey)(void*);
static void (*x_wrap_delete_PrivateKey)(void*) = _wrap_delete_PrivateKey;

void
·_swig_wrap_delete_PrivateKey(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_PrivateKey, &p);
}



#pragma dynimport _wrap_PrivateKey_swap _wrap_PrivateKey_swap ""
extern void (*_wrap_PrivateKey_swap)(void*);
static void (*x_wrap_PrivateKey_swap)(void*) = _wrap_PrivateKey_swap;

void
·_swig_wrap_PrivateKey_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_swap, &p);
}



#pragma dynimport _wrap_PrivateKey_isValid _wrap_PrivateKey_isValid ""
extern void (*_wrap_PrivateKey_isValid)(void*);
static void (*x_wrap_PrivateKey_isValid)(void*) = _wrap_PrivateKey_isValid;

void
·_swig_wrap_PrivateKey_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_isValid, &p);
}



#pragma dynimport _wrap_PrivateKey_create _wrap_PrivateKey_create ""
extern void (*_wrap_PrivateKey_create)(void*);
static void (*x_wrap_PrivateKey_create)(void*) = _wrap_PrivateKey_create;

void
·_swig_wrap_PrivateKey_create(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_create, &p);
}



#pragma dynimport _wrap_PrivateKey_save _wrap_PrivateKey_save ""
extern void (*_wrap_PrivateKey_save)(void*);
static void (*x_wrap_PrivateKey_save)(void*) = _wrap_PrivateKey_save;

void
·_swig_wrap_PrivateKey_save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_save, &p);
}



#pragma dynimport _wrap_PrivateKey_load _wrap_PrivateKey_load ""
extern void (*_wrap_PrivateKey_load)(void*);
static void (*x_wrap_PrivateKey_load)(void*) = _wrap_PrivateKey_load;

void
·_swig_wrap_PrivateKey_load(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_load, &p);
}



#pragma dynimport _wrap_PrivateKey_pubkey _wrap_PrivateKey_pubkey ""
extern void (*_wrap_PrivateKey_pubkey)(void*);
static void (*x_wrap_PrivateKey_pubkey)(void*) = _wrap_PrivateKey_pubkey;

void
·_swig_wrap_PrivateKey_pubkey(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrivateKey_pubkey, &p);
}



#pragma dynimport _wrap_new_Host__SWIG_0 _wrap_new_Host__SWIG_0 ""
extern void (*_wrap_new_Host__SWIG_0)(void*);
static void (*x_wrap_new_Host__SWIG_0)(void*) = _wrap_new_Host__SWIG_0;

void
·_swig_wrap_new_Host__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Host__SWIG_0, &p);
}



#pragma dynimport _wrap_new_Host__SWIG_1 _wrap_new_Host__SWIG_1 ""
extern void (*_wrap_new_Host__SWIG_1)(void*);
static void (*x_wrap_new_Host__SWIG_1)(void*) = _wrap_new_Host__SWIG_1;

void
·_swig_wrap_new_Host__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Host__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_Host _wrap_delete_Host ""
extern void (*_wrap_delete_Host)(void*);
static void (*x_wrap_delete_Host)(void*) = _wrap_delete_Host;

void
·_swig_wrap_delete_Host(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Host, &p);
}



#pragma dynimport _wrap_Host_swap _wrap_Host_swap ""
extern void (*_wrap_Host_swap)(void*);
static void (*x_wrap_Host_swap)(void*) = _wrap_Host_swap;

void
·_swig_wrap_Host_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_swap, &p);
}



#pragma dynimport _wrap_Host_isValid _wrap_Host_isValid ""
extern void (*_wrap_Host_isValid)(void*);
static void (*x_wrap_Host_isValid)(void*) = _wrap_Host_isValid;

void
·_swig_wrap_Host_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_isValid, &p);
}



#pragma dynimport _wrap_Host_connect _wrap_Host_connect ""
extern void (*_wrap_Host_connect)(void*);
static void (*x_wrap_Host_connect)(void*) = _wrap_Host_connect;

void
·_swig_wrap_Host_connect(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_connect, &p);
}



#pragma dynimport _wrap_Host_listen _wrap_Host_listen ""
extern void (*_wrap_Host_listen)(void*);
static void (*x_wrap_Host_listen)(void*) = _wrap_Host_listen;

void
·_swig_wrap_Host_listen(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_listen, &p);
}



#pragma dynimport _wrap_Host_unlisten _wrap_Host_unlisten ""
extern void (*_wrap_Host_unlisten)(void*);
static void (*x_wrap_Host_unlisten)(void*) = _wrap_Host_unlisten;

void
·_swig_wrap_Host_unlisten(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_unlisten, &p);
}



#pragma dynimport _wrap_Host_key _wrap_Host_key ""
extern void (*_wrap_Host_key)(void*);
static void (*x_wrap_Host_key)(void*) = _wrap_Host_key;

void
·_swig_wrap_Host_key(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_key, &p);
}



#pragma dynimport _wrap_Host_keyStr _wrap_Host_keyStr ""
extern void (*_wrap_Host_keyStr)(void*);
static void (*x_wrap_Host_keyStr)(void*) = _wrap_Host_keyStr;

void
·_swig_wrap_Host_keyStr(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_Host_keyStr, &p);
}



#pragma dynimport _wrap_Host_address _wrap_Host_address ""
extern void (*_wrap_Host_address)(void*);
static void (*x_wrap_Host_address)(void*) = _wrap_Host_address;

void
·_swig_wrap_Host_address(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_address, &p);
}



#pragma dynimport _wrap_Host_toString _wrap_Host_toString ""
extern void (*_wrap_Host_toString)(void*);
static void (*x_wrap_Host_toString)(void*) = _wrap_Host_toString;

void
·_swig_wrap_Host_toString(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_Host_toString, &p);
}



#pragma dynimport _wrap_Host_inStreams _wrap_Host_inStreams ""
extern void (*_wrap_Host_inStreams)(void*);
static void (*x_wrap_Host_inStreams)(void*) = _wrap_Host_inStreams;

void
·_swig_wrap_Host_inStreams(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_inStreams, &p);
}



#pragma dynimport _wrap_Host_outStreams _wrap_Host_outStreams ""
extern void (*_wrap_Host_outStreams)(void*);
static void (*x_wrap_Host_outStreams)(void*) = _wrap_Host_outStreams;

void
·_swig_wrap_Host_outStreams(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_outStreams, &p);
}



#pragma dynimport _wrap_Host_queuedOutOfOrder _wrap_Host_queuedOutOfOrder ""
extern void (*_wrap_Host_queuedOutOfOrder)(void*);
static void (*x_wrap_Host_queuedOutOfOrder)(void*) = _wrap_Host_queuedOutOfOrder;

void
·_swig_wrap_Host_queuedOutOfOrder(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_queuedOutOfOrder, &p);
}



#pragma dynimport _wrap_Host_queuedUnread _wrap_Host_queuedUnread ""
extern void (*_wrap_Host_queuedUnread)(void*);
static void (*x_wrap_Host_queuedUnread)(void*) = _wrap_Host_queuedUnread;

void
·_swig_wrap_Host_queuedUnread(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_queuedUnread, &p);
}



#pragma dynimport _wrap_Host_queuedInflight _wrap_Host_queuedInflight ""
extern void (*_wrap_Host_queuedInflight)(void*);
static void (*x_wrap_Host_queuedInflight)(void*) = _wrap_Host_queuedInflight;

void
·_swig_wrap_Host_queuedInflight(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_queuedInflight, &p);
}



#pragma dynimport _wrap_Host_queuedToRetransmit _wrap_Host_queuedToRetransmit ""
extern void (*_wrap_Host_queuedToRetransmit)(void*);
static void (*x_wrap_Host_queuedToRetransmit)(void*) = _wrap_Host_queuedToRetransmit;

void
·_swig_wrap_Host_queuedToRetransmit(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_queuedToRetransmit, &p);
}



#pragma dynimport _wrap_Host_bytesReceived _wrap_Host_bytesReceived ""
extern void (*_wrap_Host_bytesReceived)(void*);
static void (*x_wrap_Host_bytesReceived)(void*) = _wrap_Host_bytesReceived;

void
·_swig_wrap_Host_bytesReceived(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_bytesReceived, &p);
}



#pragma dynimport _wrap_Host_bytesSent _wrap_Host_bytesSent ""
extern void (*_wrap_Host_bytesSent)(void*);
static void (*x_wrap_Host_bytesSent)(void*) = _wrap_Host_bytesSent;

void
·_swig_wrap_Host_bytesSent(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_bytesSent, &p);
}



#pragma dynimport _wrap_Host_lastReceive _wrap_Host_lastReceive ""
extern void (*_wrap_Host_lastReceive)(void*);
static void (*x_wrap_Host_lastReceive)(void*) = _wrap_Host_lastReceive;

void
·_swig_wrap_Host_lastReceive(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_lastReceive, &p);
}



#pragma dynimport _wrap_Host_lastSend _wrap_Host_lastSend ""
extern void (*_wrap_Host_lastSend)(void*);
static void (*x_wrap_Host_lastSend)(void*) = _wrap_Host_lastSend;

void
·_swig_wrap_Host_lastSend(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Host_lastSend, &p);
}



#pragma dynimport _wrap_Channel_address _wrap_Channel_address ""
extern void (*_wrap_Channel_address)(void*);
static void (*x_wrap_Channel_address)(void*) = _wrap_Channel_address;

void
·_swig_wrap_Channel_address(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Channel_address, &p);
}



#pragma dynimport _wrap_Channel_host _wrap_Channel_host ""
extern void (*_wrap_Channel_host)(void*);
static void (*x_wrap_Channel_host)(void*) = _wrap_Channel_host;

void
·_swig_wrap_Channel_host(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Channel_host, &p);
}



#pragma dynimport _wrap_new_Channel _wrap_new_Channel ""
extern void (*_wrap_new_Channel)(void*);
static void (*x_wrap_new_Channel)(void*) = _wrap_new_Channel;

void
·_swig_wrap_new_Channel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Channel, &p);
}



#pragma dynimport _wrap_delete_Channel _wrap_delete_Channel ""
extern void (*_wrap_delete_Channel)(void*);
static void (*x_wrap_delete_Channel)(void*) = _wrap_delete_Channel;

void
·_swig_wrap_delete_Channel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Channel, &p);
}



#pragma dynimport _wrap_new_Abortable__SWIG_0 _wrap_new_Abortable__SWIG_0 ""
extern void (*_wrap_new_Abortable__SWIG_0)(void*);
static void (*x_wrap_new_Abortable__SWIG_0)(void*) = _wrap_new_Abortable__SWIG_0;

void
·_swig_wrap_new_Abortable__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Abortable__SWIG_0, &p);
}



#pragma dynimport _wrap_new_Abortable__SWIG_1 _wrap_new_Abortable__SWIG_1 ""
extern void (*_wrap_new_Abortable__SWIG_1)(void*);
static void (*x_wrap_new_Abortable__SWIG_1)(void*) = _wrap_new_Abortable__SWIG_1;

void
·_swig_wrap_new_Abortable__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Abortable__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_Abortable _wrap_delete_Abortable ""
extern void (*_wrap_delete_Abortable)(void*);
static void (*x_wrap_delete_Abortable)(void*) = _wrap_delete_Abortable;

void
·_swig_wrap_delete_Abortable(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Abortable, &p);
}



#pragma dynimport _wrap_Abortable_swap _wrap_Abortable_swap ""
extern void (*_wrap_Abortable_swap)(void*);
static void (*x_wrap_Abortable_swap)(void*) = _wrap_Abortable_swap;

void
·_swig_wrap_Abortable_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Abortable_swap, &p);
}



#pragma dynimport _wrap_Abortable_isValid _wrap_Abortable_isValid ""
extern void (*_wrap_Abortable_isValid)(void*);
static void (*x_wrap_Abortable_isValid)(void*) = _wrap_Abortable_isValid;

void
·_swig_wrap_Abortable_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Abortable_isValid, &p);
}



#pragma dynimport _wrap_Abortable_abort _wrap_Abortable_abort ""
extern void (*_wrap_Abortable_abort)(void*);
static void (*x_wrap_Abortable_abort)(void*) = _wrap_Abortable_abort;

void
·_swig_wrap_Abortable_abort(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Abortable_abort, &p);
}



#pragma dynimport _wrap_EndPoint_create__SWIG_0 _wrap_EndPoint_create__SWIG_0 ""
extern void (*_wrap_EndPoint_create__SWIG_0)(void*);
static void (*x_wrap_EndPoint_create__SWIG_0)(void*) = _wrap_EndPoint_create__SWIG_0;

void
·_swig_wrap_EndPoint_create__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_create__SWIG_0, &p);
}



#pragma dynimport _wrap_EndPoint_create__SWIG_1 _wrap_EndPoint_create__SWIG_1 ""
extern void (*_wrap_EndPoint_create__SWIG_1)(void*);
static void (*x_wrap_EndPoint_create__SWIG_1)(void*) = _wrap_EndPoint_create__SWIG_1;

void
·_swig_wrap_EndPoint_create__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_create__SWIG_1, &p);
}



#pragma dynimport _wrap_EndPoint_create__SWIG_2 _wrap_EndPoint_create__SWIG_2 ""
extern void (*_wrap_EndPoint_create__SWIG_2)(void*);
static void (*x_wrap_EndPoint_create__SWIG_2)(void*) = _wrap_EndPoint_create__SWIG_2;

void
·_swig_wrap_EndPoint_create__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_create__SWIG_2, &p);
}



#pragma dynimport _wrap_EndPoint_create__SWIG_3 _wrap_EndPoint_create__SWIG_3 ""
extern void (*_wrap_EndPoint_create__SWIG_3)(void*);
static void (*x_wrap_EndPoint_create__SWIG_3)(void*) = _wrap_EndPoint_create__SWIG_3;

void
·_swig_wrap_EndPoint_create__SWIG_3(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_create__SWIG_3, &p);
}



#pragma dynimport _wrap_EndPoint_create__SWIG_4 _wrap_EndPoint_create__SWIG_4 ""
extern void (*_wrap_EndPoint_create__SWIG_4)(void*);
static void (*x_wrap_EndPoint_create__SWIG_4)(void*) = _wrap_EndPoint_create__SWIG_4;

void
·_swig_wrap_EndPoint_create__SWIG_4(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_create__SWIG_4, &p);
}



#pragma dynimport _wrap_new_EndPoint__SWIG_0 _wrap_new_EndPoint__SWIG_0 ""
extern void (*_wrap_new_EndPoint__SWIG_0)(void*);
static void (*x_wrap_new_EndPoint__SWIG_0)(void*) = _wrap_new_EndPoint__SWIG_0;

void
·_swig_wrap_new_EndPoint__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_EndPoint__SWIG_0, &p);
}



#pragma dynimport _wrap_new_EndPoint__SWIG_1 _wrap_new_EndPoint__SWIG_1 ""
extern void (*_wrap_new_EndPoint__SWIG_1)(void*);
static void (*x_wrap_new_EndPoint__SWIG_1)(void*) = _wrap_new_EndPoint__SWIG_1;

void
·_swig_wrap_new_EndPoint__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_EndPoint__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_EndPoint _wrap_delete_EndPoint ""
extern void (*_wrap_delete_EndPoint)(void*);
static void (*x_wrap_delete_EndPoint)(void*) = _wrap_delete_EndPoint;

void
·_swig_wrap_delete_EndPoint(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_EndPoint, &p);
}



#pragma dynimport _wrap_EndPoint_swap _wrap_EndPoint_swap ""
extern void (*_wrap_EndPoint_swap)(void*);
static void (*x_wrap_EndPoint_swap)(void*) = _wrap_EndPoint_swap;

void
·_swig_wrap_EndPoint_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_swap, &p);
}



#pragma dynimport _wrap_EndPoint_isValid _wrap_EndPoint_isValid ""
extern void (*_wrap_EndPoint_isValid)(void*);
static void (*x_wrap_EndPoint_isValid)(void*) = _wrap_EndPoint_isValid;

void
·_swig_wrap_EndPoint_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_isValid, &p);
}



#pragma dynimport _wrap_EndPoint_destroy _wrap_EndPoint_destroy ""
extern void (*_wrap_EndPoint_destroy)(void*);
static void (*x_wrap_EndPoint_destroy)(void*) = _wrap_EndPoint_destroy;

void
·_swig_wrap_EndPoint_destroy(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_destroy, &p);
}



#pragma dynimport _wrap_EndPoint_whenSafeToDestroy _wrap_EndPoint_whenSafeToDestroy ""
extern void (*_wrap_EndPoint_whenSafeToDestroy)(void*);
static void (*x_wrap_EndPoint_whenSafeToDestroy)(void*) = _wrap_EndPoint_whenSafeToDestroy;

void
·_swig_wrap_EndPoint_whenSafeToDestroy(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_whenSafeToDestroy, &p);
}



#pragma dynimport _wrap_EndPoint_setRate _wrap_EndPoint_setRate ""
extern void (*_wrap_EndPoint_setRate)(void*);
static void (*x_wrap_EndPoint_setRate)(void*) = _wrap_EndPoint_setRate;

void
·_swig_wrap_EndPoint_setRate(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_setRate, &p);
}



#pragma dynimport _wrap_EndPoint_key _wrap_EndPoint_key ""
extern void (*_wrap_EndPoint_key)(void*);
static void (*x_wrap_EndPoint_key)(void*) = _wrap_EndPoint_key;

void
·_swig_wrap_EndPoint_key(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_key, &p);
}



#pragma dynimport _wrap_EndPoint_publicKeyStr _wrap_EndPoint_publicKeyStr ""
extern void (*_wrap_EndPoint_publicKeyStr)(void*);
static void (*x_wrap_EndPoint_publicKeyStr)(void*) = _wrap_EndPoint_publicKeyStr;

void
·_swig_wrap_EndPoint_publicKeyStr(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_publicKeyStr, &p);
}



#pragma dynimport _wrap_EndPoint_bytesSent _wrap_EndPoint_bytesSent ""
extern void (*_wrap_EndPoint_bytesSent)(void*);
static void (*x_wrap_EndPoint_bytesSent)(void*) = _wrap_EndPoint_bytesSent;

void
·_swig_wrap_EndPoint_bytesSent(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_bytesSent, &p);
}



#pragma dynimport _wrap_EndPoint_bytesReceived _wrap_EndPoint_bytesReceived ""
extern void (*_wrap_EndPoint_bytesReceived)(void*);
static void (*x_wrap_EndPoint_bytesReceived)(void*) = _wrap_EndPoint_bytesReceived;

void
·_swig_wrap_EndPoint_bytesReceived(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_bytesReceived, &p);
}



#pragma dynimport _wrap_EndPoint_contact _wrap_EndPoint_contact ""
extern void (*_wrap_EndPoint_contact)(void*);
static void (*x_wrap_EndPoint_contact)(void*) = _wrap_EndPoint_contact;

void
·_swig_wrap_EndPoint_contact(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_contact, &p);
}



#pragma dynimport _wrap_EndPoint_hosts _wrap_EndPoint_hosts ""
extern void (*_wrap_EndPoint_hosts)(void*);
static void (*x_wrap_EndPoint_hosts)(void*) = _wrap_EndPoint_hosts;

void
·_swig_wrap_EndPoint_hosts(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_hosts, &p);
}



#pragma dynimport _wrap_EndPoint_channels _wrap_EndPoint_channels ""
extern void (*_wrap_EndPoint_channels)(void*);
static void (*x_wrap_EndPoint_channels)(void*) = _wrap_EndPoint_channels;

void
·_swig_wrap_EndPoint_channels(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_channels, &p);
}



#pragma dynimport _wrap_EndPoint_advertise _wrap_EndPoint_advertise ""
extern void (*_wrap_EndPoint_advertise)(void*);
static void (*x_wrap_EndPoint_advertise)(void*) = _wrap_EndPoint_advertise;

void
·_swig_wrap_EndPoint_advertise(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_advertise, &p);
}



#pragma dynimport _wrap_EndPoint_unadvertise _wrap_EndPoint_unadvertise ""
extern void (*_wrap_EndPoint_unadvertise)(void*);
static void (*x_wrap_EndPoint_unadvertise)(void*) = _wrap_EndPoint_unadvertise;

void
·_swig_wrap_EndPoint_unadvertise(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_EndPoint_unadvertise, &p);
}



#pragma dynimport _wrap_Event_create _wrap_Event_create ""
extern void (*_wrap_Event_create)(void*);
static void (*x_wrap_Event_create)(void*) = _wrap_Event_create;

void
·_swig_wrap_Event_create(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_create, &p);
}



#pragma dynimport _wrap_Event_schedule _wrap_Event_schedule ""
extern void (*_wrap_Event_schedule)(void*);
static void (*x_wrap_Event_schedule)(void*) = _wrap_Event_schedule;

void
·_swig_wrap_Event_schedule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_schedule, &p);
}



#pragma dynimport _wrap_Event_scheduleIn _wrap_Event_scheduleIn ""
extern void (*_wrap_Event_scheduleIn)(void*);
static void (*x_wrap_Event_scheduleIn)(void*) = _wrap_Event_scheduleIn;

void
·_swig_wrap_Event_scheduleIn(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_scheduleIn, &p);
}



#pragma dynimport _wrap_Event_time _wrap_Event_time ""
extern void (*_wrap_Event_time)(void*);
static void (*x_wrap_Event_time)(void*) = _wrap_Event_time;

void
·EventTime(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_time, &p);
}



#pragma dynimport _wrap_new_Event__SWIG_0 _wrap_new_Event__SWIG_0 ""
extern void (*_wrap_new_Event__SWIG_0)(void*);
static void (*x_wrap_new_Event__SWIG_0)(void*) = _wrap_new_Event__SWIG_0;

void
·_swig_wrap_new_Event__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Event__SWIG_0, &p);
}



#pragma dynimport _wrap_new_Event__SWIG_1 _wrap_new_Event__SWIG_1 ""
extern void (*_wrap_new_Event__SWIG_1)(void*);
static void (*x_wrap_new_Event__SWIG_1)(void*) = _wrap_new_Event__SWIG_1;

void
·_swig_wrap_new_Event__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Event__SWIG_1, &p);
}



#pragma dynimport _wrap_new_Event__SWIG_2 _wrap_new_Event__SWIG_2 ""
extern void (*_wrap_new_Event__SWIG_2)(void*);
static void (*x_wrap_new_Event__SWIG_2)(void*) = _wrap_new_Event__SWIG_2;

void
·_swig_wrap_new_Event__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Event__SWIG_2, &p);
}



#pragma dynimport _wrap_delete_Event _wrap_delete_Event ""
extern void (*_wrap_delete_Event)(void*);
static void (*x_wrap_delete_Event)(void*) = _wrap_delete_Event;

void
·_swig_wrap_delete_Event(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Event, &p);
}



#pragma dynimport _wrap_Event_swap _wrap_Event_swap ""
extern void (*_wrap_Event_swap)(void*);
static void (*x_wrap_Event_swap)(void*) = _wrap_Event_swap;

void
·_swig_wrap_Event_swap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_swap, &p);
}



#pragma dynimport _wrap_Event_isValid _wrap_Event_isValid ""
extern void (*_wrap_Event_isValid)(void*);
static void (*x_wrap_Event_isValid)(void*) = _wrap_Event_isValid;

void
·_swig_wrap_Event_isValid(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_isValid, &p);
}



#pragma dynimport _wrap_Event_reschedule _wrap_Event_reschedule ""
extern void (*_wrap_Event_reschedule)(void*);
static void (*x_wrap_Event_reschedule)(void*) = _wrap_Event_reschedule;

void
·_swig_wrap_Event_reschedule(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_reschedule, &p);
}



#pragma dynimport _wrap_Event_rescheduleIn _wrap_Event_rescheduleIn ""
extern void (*_wrap_Event_rescheduleIn)(void*);
static void (*x_wrap_Event_rescheduleIn)(void*) = _wrap_Event_rescheduleIn;

void
·_swig_wrap_Event_rescheduleIn(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_rescheduleIn, &p);
}



#pragma dynimport _wrap_Event_cancel _wrap_Event_cancel ""
extern void (*_wrap_Event_cancel)(void*);
static void (*x_wrap_Event_cancel)(void*) = _wrap_Event_cancel;

void
·_swig_wrap_Event_cancel(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_cancel, &p);
}



#pragma dynimport _wrap_Event_timeOfExecution _wrap_Event_timeOfExecution ""
extern void (*_wrap_Event_timeOfExecution)(void*);
static void (*x_wrap_Event_timeOfExecution)(void*) = _wrap_Event_timeOfExecution;

void
·_swig_wrap_Event_timeOfExecution(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_timeOfExecution, &p);
}



#pragma dynimport _wrap_Event_timeTillExecution _wrap_Event_timeTillExecution ""
extern void (*_wrap_Event_timeTillExecution)(void*);
static void (*x_wrap_Event_timeTillExecution)(void*) = _wrap_Event_timeTillExecution;

void
·_swig_wrap_Event_timeTillExecution(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_timeTillExecution, &p);
}



#pragma dynimport _wrap_Event_isScheduled _wrap_Event_isScheduled ""
extern void (*_wrap_Event_isScheduled)(void*);
static void (*x_wrap_Event_isScheduled)(void*) = _wrap_Event_isScheduled;

void
·_swig_wrap_Event_isScheduled(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Event_isScheduled, &p);
}



