#! /bin/sh

dir=`dirname "$0"`
mlton=`which mlton`
eval `grep "^lib=" "${mlton}"`

export MLTON_LIB_DIR="$lib"
exec ${mlton} \
	-ar-script "$dir/static-library" \
	-target-link-opt linux "-L$dir/linux" \
	-target-link-opt mingw "-L$dir/mingw" \
	-target-link-opt amd64 "-lbs-asm-amd64" \
	-target-link-opt x86   "-lbs-asm-x86" \
	"$@"
